{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openclaw.pvcName" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
    {{- with .Values.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    csi.storage.k8s.io/fstype: {{ .Values.persistence.csiFsType | default "obsfs" }}
    {{- if .Values.persistence.csiSecretName }}
    csi.storage.k8s.io/node-publish-secret-name: {{ .Values.persistence.csiSecretName }}
    csi.storage.k8s.io/node-publish-secret-namespace: {{ .Values.persistence.csiSecretNamespace | default $.Release.Namespace }}
    {{- end }}
    {{- with .Values.persistence.annotations }}
    {{- toYaml . }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
